# Upstream changes from _extends are only recognized when modifications are made to this file in the default branch.
_extends: .github
repository:
  name: terraform-aws-rds
  description: ' Terraform module to provision AWS RDS instances'
  homepage: https://cloudposse.com/accelerate
  topics: terraform, terraform-modules, rds, aws-rds, postgres, mysql, aws, hcl2
